default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: snapshot_development

test:
  <<: *default
  database: snapshot_test

production:
  <<: *default
  database: snapshot_production
